name: Deploy to Beam

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set environment variables
        id: set-vars
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/master' ]]; then
            echo "::set-output name=client_id::${{ vars.PRODUCTION_BEAM_CLIENT_ID }}"
            echo "::set-output name=client_secret::${{ secrets.PRODUCTION_BEAM_CLIENT_SECRET }}"
            echo "::set-output name=profile::production"
          elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
            echo "::set-output name=client_id::${{ vars.STAGING_BEAM_CLIENT_ID }}"
            echo "::set-output name=client_secret::${{ secrets.STAGING_BEAM_CLIENT_SECRET }}"
            echo "::set-output name=profile::staging"
          fi

      - name: Authenticate and Deploy to Beam
        env:
          BEAM_CLIENT_ID: ${{ steps.set-vars.outputs.client_id }}
          BEAM_CLIENT_SECRET: ${{ steps.set-vars.outputs.client_secret }}
          PROFILE: ${{ steps.set-vars.outputs.profile }}
        run: |
          echo "Using profile '$PROFILE'"
          curl https://raw.githubusercontent.com/slai-labs/get-beam/main/get-beam.sh -sSfL | sh
          pip3 install --upgrade pip
          pip3 install beam-sdk
          pip3 install fastapi

          echo "beam configure --clientId $BEAM_CLIENT_ID --clientSecret $BEAM_CLIENT_SECRET --profileName $PROFILE"
          beam configure --clientId $BEAM_CLIENT_ID --clientSecret $BEAM_CLIENT_SECRET --profileName $PROFILE
          cd story-viz/backend
          STAGE=$PROFILE ./beam_wrapper.sh deploy beam_api.py:handler --profileName $PROFILE
